/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "arraydb_constants.h"

namespace arraydb {

const arraydbConstants g_arraydb_constants;

arraydbConstants::arraydbConstants() {
}

} // namespace

