/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef arraydb_CONSTANTS_H
#define arraydb_CONSTANTS_H

#include "arraydb_types.h"

namespace arraydb {

class arraydbConstants {
 public:
  arraydbConstants();

};

extern const arraydbConstants g_arraydb_constants;

} // namespace

#endif
